function run_power_ssm_scalar_r_all_bands()
%RUN_POWER_SSM_SCALAR_R_ALL_BANDS Run scalar-r SSM for delta/theta/alpha.
%
% Requires:
%   outputs/power_table_for_ssm_subepochs_collapsed.csv
%
% This wrapper keeps the SSM code identical across bands. Only the power
% column and frequency labels change.

repoRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(repoRoot, '3_run_analyses'));

inputTable = "power_table_for_ssm_subepochs_collapsed.csv";
bands = struct( ...
    'bandName', {'delta', 'theta', 'alpha'}, ...
    'bandLowHz', {1, 4, 8}, ...
    'bandHighHz', {4, 8, 12}, ...
    'powerColumn', {'delta_dB', 'theta_dB', 'alpha_dB'});

for bandIdx = 1:numel(bands)
    band = bands(bandIdx);
    fprintf('\n============================================================\n');
    fprintf('Scalar-r power SSM: %s [%g, %g] Hz\n', ...
        band.bandName, band.bandLowHz, band.bandHighHz);
    fprintf('============================================================\n');

    run_power_ssm_scalar_r( ...
        'bandName', string(band.bandName), ...
        'bandLowHz', band.bandLowHz, ...
        'bandHighHz', band.bandHighHz, ...
        'inputTable', inputTable, ...
        'powerColumn', string(band.powerColumn), ...
        'qMode', "all", ...
        'outputPrefix', "power_ssm");
end
end
